// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbb5VymqtxkizEDW5gvrSUG7aqiTz5bY',
    appId: '1:818186152052:web:e4b70b9a768a38223a8921',
    messagingSenderId: '818186152052',
    projectId: 'kafesiparis-47b18',
    authDomain: 'kafesiparis-47b18.firebaseapp.com',
    storageBucket: 'kafesiparis-47b18.firebasestorage.app',
    measurementId: 'G-E5EP82HH97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWZK64QADakMDIuba6yPKOJEzAE3qs3U',
    appId: '1:818186152052:android:64f7ec5351677e2d3a8921',
    messagingSenderId: '818186152052',
    projectId: 'kafesiparis-47b18',
    storageBucket: 'kafesiparis-47b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrl5M5c6xxlU9M5dUj7zaArO-pyr4uoqE',
    appId: '1:818186152052:ios:393cc02ce6aa7a333a8921',
    messagingSenderId: '818186152052',
    projectId: 'kafesiparis-47b18',
    storageBucket: 'kafesiparis-47b18.firebasestorage.app',
    iosBundleId: 'com.example.kafeSiparisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrl5M5c6xxlU9M5dUj7zaArO-pyr4uoqE',
    appId: '1:818186152052:ios:393cc02ce6aa7a333a8921',
    messagingSenderId: '818186152052',
    projectId: 'kafesiparis-47b18',
    storageBucket: 'kafesiparis-47b18.firebasestorage.app',
    iosBundleId: 'com.example.kafeSiparisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbb5VymqtxkizEDW5gvrSUG7aqiTz5bY',
    appId: '1:818186152052:web:493aaaf3d7e0b3c33a8921',
    messagingSenderId: '818186152052',
    projectId: 'kafesiparis-47b18',
    authDomain: 'kafesiparis-47b18.firebaseapp.com',
    storageBucket: 'kafesiparis-47b18.firebasestorage.app',
    measurementId: 'G-8TNZVYSD71',
  );
}
