name: kafe_siparis_web_panel
description: Kafe siparişlerini web üzerinden görüntüleme paneli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  cloud_firestore: ^5.0.1
  intl: ^0.19.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
